name: CI / CD
on:
  # Triggers the workflow on push for the main branch
  push:
    branches:
      - masterbranch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'ap-south-1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy to AWS S3"
        run: aws s3 cp ./text-file.txt s3://sambandham-tf-bucket/text-file.txt